version: '3.2'
services:
  treelogy-sso-prometheus-local:
    image: prom/prometheus:latest
    restart: always
    container_name: treelogy-sso-prometheus-local
    ports:
    - 9090:9090
    command:
    - --config.file=/treelogy-sso-server-log/prometheus.yml
    volumes:
    - ./prometheus.yml:/treelogy-sso-server-log/prometheus.yml
  treelogy-sso-grafana-local:
    image: grafana/grafana:latest
    container_name: treelogy-sso-grafana-local
    restart: always
    ports:
    - 3000:3000
    environment:
        - GF_SECURITY_ADMIN_PASSWORD=pass
    volumes:
        - grafana_data:/var/lib/grafana
    depends_on:
        - prometheus
  treelogy-sso-zipkin-local:
    image: openzipkin/zipkin:latest
    container_name: treelogy-sso-zipkin-local
    restart: always
    ports:
    - 9411:9411
volumes:
    grafana_data: {}