version: '3.2'
networks:
  default:
    external: true
    name: treelogy-sso-net

services:
  treelogy-sso-wso2:
    image: wso2/wso2is:latest
    container_name: treelogy-sso-wso
    ports:
    - 9443:9443
    links:
      - treelogy-sso-db-wso2-pg12
    depends_on:
      - treelogy-sso-db-wso2-pg12
  treelogy-sso-wso2-api:
      build: ./sso-api-idp/
      container_name: treelogy-sso-wso2-api
      links:
        - treelogy-sso-db-wso2-pg12
      depends_on:
        - treelogy-sso-db-wso2-pg12
  treelogy-sso-db-wso2-pg12:
    image: postgres:12-alpine
    container_name: treelogy-sso-db-wso2-pg12
    hostname: postgres
    tty: true
    ports:
      - 5440:5432
    volumes:
      - .dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=@sso@wso2
      - POSTGRES_DB=db_sso_wso2-user
      - POSTGRES_USER=sso-treelogy