version: '3.2'
services:
  treelogy-sso-wso2:
    image: wso2/wso2is:latest
    container_name: treelogy-sso-wso2-local
    ports:
    - 9443:9443
    links:
      - treelogy-sso-db-wso2-pg12
    depends_on:
      - treelogy-sso-db-wso2-pg12
  treelogy-sso-db-wso2-pg12:
    image: postgres:12-alpine
    container_name: treelogy-sso-db-wso2-pg12-local
    hostname: postgres
    tty: true
    ports:
      - 5440:5432
    volumes:
      - .dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=@sso@wso2
      - POSTGRES_DB=db_sso_wso2-user
      - POSTGRES_USER=sso-treelogy