version: '3.2'
networks:
  default:
    external: true
    name: treelogy-sso-net
services:
  treelogy-sso-prometheus:
    image: prom/prometheus:latest
    restart: always
    container_name: treelogy-sso-prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/treelogy-sso-server-log/prometheus.yml
    volumes:
    - ./prometheus.yml:/treelogy-sso-server-log/prometheus.yml
  treelogy-sso-grafana:
    image: grafana/grafana:latest
    container_name: treelogy-sso-grafana
    restart: always
    ports:
    - 3000:3000
    environment:
        - GF_SECURITY_ADMIN_PASSWORD=pass
    volumes:
        - grafana_data:/var/lib/grafana
    depends_on:
        - prometheus
  treelogy-sso-zipkin:
    image: openzipkin/zipkin:latest
    container_name: treelogy-sso-zipkin
    restart: always
    ports:
    - 9411:9411
volumes:
    grafana_data: {}