version: '3.2'
services:
  treelogy-sso-rabbitmq:
      image: rabbitmq:3.9.13-management-alpine
      container_name: treelogy-sso-rabbitmq-local
      ports:
      - 5672:5672
      - 15672:15672
      volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  treelogy-sso-integration:
    build: .
    container_name: treelogy-sso-integration-local