version: '3.2'
networks:
  default:
    external: true
    name: treelogy-sso-net
services:
  treelogy-sso-watchtower:
    image: v2tec/watchtower
    container_name: treelogy-sso-watchtower
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    restart: always